<?php

declare(strict_types=1);

namespace App\StateMachines\Reservations;

final class CancelledState extends BaseBookingStateMachine
{
    public function refunded(): never
    {
        parent::refunded(); // TODO: Change the autogenerated stub
    }
}
