<?php

declare(strict_types=1);

namespace App\StateMachines\Reservations;

final class CheckedOutState extends BaseBookingStateMachine
{
    public function finalized(): never
    {
        parent::finalized(); // TODO: Change the autogenerated stub
    }
}
