<?php

declare(strict_types=1);

namespace App\StateMachines\Reservations;

final class ConfirmedState extends BaseBookingStateMachine
{
    public function paid(): never
    {
        parent::paid(); // TODO: Change the autogenerated stub
    }

    public function cancelled(): never
    {
        parent::cancelled(); // TODO: Change the autogenerated stub
    }
}
