<?php

declare(strict_types=1);

namespace App\StateMachines\Reservations;

final class PaidState extends BaseBookingStateMachine
{
    public function cancelled(): never
    {
        parent::cancelled(); // TODO: Change the autogenerated stub
    }

    public function checkedIn(): never
    {
        parent::checkedIn(); // TODO: Change the autogenerated stub
    }
}
