<?php

declare(strict_types=1);

namespace App\StateMachines\Reservations;

use App\Enums\BookingStatus;

final class PaidState extends BaseBookingStateMachine
{
    public function cancelled(): void
    {
        parent::cancelled(); // TODO: Change the autogenerated stub
    }

    public function checkedIn(): void
    {
        $this->booking->update(
            attributes: [
                'status' => BookingStatus::CheckedIn,
            ],
        );
    }
}
